### ISSUE TITLE
“从源文件部署到服务器":无法加载页面

### ISSUE THREAD

**Issue by luyanci** [animation-picker/genshin-impact#72]
本人使用的是按教程文档中的“从源文件部署到服务器”，文件成功下载在指定目录且宝塔内已更新站点运行目录。但访问页面加载不出来是什么原因，一动不动的，求助大佬

_最初由 XavierBex 在 https://github.com/animation-picker/genshin-impact/issues/53#issuecomment-2213050135 发布_

**Comment by XavierBex** [comment]
http://xavierbe.cn:8000/

**Comment by XavierBex** [comment]
一直显示在Loading

**Comment by XavierBex** [comment]
![Uploading IMG_6124.jpeg…]()

**Comment by XavierBex** [comment]
![Uploading IMG_6124.jpeg…]()

**Comment by XavierBex** [comment]
站点运行目录设置图
![Uploading IMG_6124.jpeg…]()

**Comment by XavierBex** [comment]
![IMG_6124](https://github.com/animation-picker/genshin-impact/assets/94225562/68e76b0b-37a4-421f-b38a-5cd22cf9a9f0)

**Comment by XavierBex** [comment]
![IMG_6125](https://github.com/animation-picker/genshin-impact/assets/94225562/d3171058-da0b-4249-a154-3c4b946d1e75)

**Comment by luyanci** [comment]
![Screenshot_2024-07-08-14-15-29-700_com.realvnc.viewer.android.jpg](https://github.com/animation-picker/genshin-impact/assets/68143180/fb32977b-29d5-4605-b979-878d281af1ae)

嘶…也许得重新构建一下页面…

**Comment by XavierBex** [comment]
那现在咋整，/捂脸

**Comment by luyanci** [comment]
> 那现在咋整，/捂脸

你git pull一下看看

**Comment by XavierBex** [comment]
可以了可以了，感谢
![IMG_6129](https://github.com/animation-picker/genshin-impact/assets/94225562/8cd7740b-ff0d-42b9-97b6-e72348cd3bb7)

**Comment by XavierBex** [comment]
另外还有一个问题就是名单那个能否在服务区上设置好或自动记忆浏览器上次使用的txt，每次都要手动导入一下有点小麻烦..

**Comment by luyanci** [comment]
> 另外还有一个问题就是名单那个能否在服务器上设置好或自动记忆浏览器上次使用的txt，每次都要手动导入一下有点小麻烦..

这条重复了…

**Comment by XavierBex** [comment]
> > 另外还有一个问题就是名单那个能否在服务器上设置好或自动记忆浏览器上次使用的txt，每次都要手动导入一下有点小麻烦..
> 
> 这条重复了…

啊？什么重复….

**Comment by luyanci** [comment]
#23
