### ISSUE TITLE
[BUG]点击设置图标按钮后画面无响应

### ISSUE THREAD

**Issue by XavierBex** [animation-picker/genshin-impact#74]
### BUG描述(文字/截图/视频)

如视频所示，已确保源码和github保持一致。

https://github.com/user-attachments/assets/01d4abba-c20f-4698-8a20-9352eab4d453

### 一些相关信息

win11+edge，内站服务器源码宝塔部署

### 预期行为(文字/截图/视频)

如视频

### 实际行为(文字/截图/视频)

如视频

**Comment by luyanci** [comment]
#55
