### ISSUE TITLE
 项目是否经授权用于商业用途？

### ISSUE THREAD

**Issue by windy664** [animation-picker/genshin-impact#76]
你好，

首先非常感谢你们的辛勤开发和开源贡献。最近，我发现贵项目被用于商业用途，具体情况如下：

Gitee 平台上发现了一位用户将贵项目的代码发布，并进行商业化运作。项目地址为：

https://gitee.com/gaosongsong2023/ysck

不久前，我购买了他们提供的二进制文件，但后来了解到这些内容可能是基于贵项目的内容。

作为用户，我感到担忧！

![image](https://github.com/user-attachments/assets/88682ba8-d187-41a8-95a7-b23ccf727658)

![Screenshot_2024-10-02-17-24-39-675_com tencent mm](https://github.com/user-attachments/assets/f4997c0c-56bf-4c32-a4c6-a51bcdc04cc0)

**Comment by luyanci** [comment]
> 你好，
> 
> 首先非常感谢你们的辛勤开发和开源贡献。最近，我发现贵项目被用于商业用途，具体情况如下：
> 
> Gitee 平台上发现了一位用户将贵项目的代码发布，并进行商业化运作。项目地址为：
> 
> https://gitee.com/gaosongsong2023/ysck
> 
> 不久前，我购买了他们提供的二进制文件，但后来了解到这些内容可能是基于贵项目的内容。
> 
> 作为用户，我感到担忧！
> 
> 
> ![image](https://github.com/user-attachments/assets/88682ba8-d187-41a8-95a7-b23ccf727658)
> 
> ![Screenshot_2024-10-02-17-24-39-675_com tencent mm](https://github.com/user-attachments/assets/f4997c0c-56bf-4c32-a4c6-a51bcdc04cc0)
> 

感谢提供，我去挂个issue去

**Comment by cyanial** [comment]
不反对用于商业，也不反对修改后二次售卖。但是需要标明出处。

**Comment by luyanci** [comment]
>许可证
>本项目采用'CC BY-NC-SA 4.0' 许可证，不得用于商业用途。

**Comment by luyanci** [comment]
嘶…gitee反应似乎比我都快

**Comment by luyanci** [comment]
这边留下我那边的模板，免得仓库恢复还来不及弄
```md
# 提醒
你好

我是Github[`animation-picker`](https://github.com/animation-picker)组织的管理员之一[@luyanci](https://github.com/luyanci)，这边收到关于本仓库疑似侵犯组织中的[`genshin-impact`](https://github.com/animation-picker/genshin-impact)仓库的issue

该issue中提到，本仓库违反了[`CC BY-NC-SA 4.0`](https://github.com/animation-picker/genshin-impact/blob/main/LICENSE)开源许可证协议，进行了商业活动，于是特意发起本issue

请遵守`CC BY-NC-SA 4.0`开源许可证协议，可以提供免费下载链接

## 身份证明
![animation-picker组织成员证明](https://foruda.gitee.com/images/1727864246475075362/da823d8f_7801570.png "Screenshot_2024-10-02_18_11_38.png")

```

**Comment by luyanci** [comment]
如恢复访问，请重新打开issue
