### ISSUE TITLE
docs文档无法打开

### ISSUE THREAD

**Issue by Regionnor** [animation-picker/genshin-impact#78]
### BUG描述(文字/截图/视频)

![image](https://github.com/user-attachments/assets/09a4b4d1-7d08-4468-af29-4719f2225473)

### 一些相关信息

无法打开https://docs.mznet.pro/

### 预期行为(文字/截图/视频)

正常访问网站

### 实际行为(文字/截图/视频)

无法访问此网站

**Comment by luyanci** [comment]
@Maizi-G 域名是不是过期啦

**Comment by Maizi-G** [comment]
> @Maizi-G 域名是不是过期啦

过期了
等会换

**Comment by Maizi-G** [comment]
文档链接更新完成

**Comment by Maizi-G** [comment]
@luyanci @Regionnor
