### ISSUE TITLE
怎样更改点名的卡池为常驻祈愿

### ISSUE THREAD

**Issue by Infiheaven** [animation-picker/genshin-impact#83]
很抱歉浪费您宝贵的时间，但我很需要知道如何改变这个页面的卡池为常驻祈愿
除此之外，最新的release中win基于Electron打包的应用程序在win11中无法正常打开，会卡在加载界面
![c0cec2b7b96b2bf293001bc8625f4220](https://github.com/user-attachments/assets/d8d00353-ceb1-426a-9a31-6930c88768c8)
![wanderlust-invocation-1](https://github.com/user-attachments/assets/9dadb6cb-5ea2-42dc-8963-4ee9cd9afe05)
![image](https://github.com/user-attachments/assets/e8e3a586-09db-4634-af87-4a65c349c5f4)

**Comment by luyanci** [comment]
更改会常驻祈愿的话 直接revert掉a04dbef89465077f4d33cce9d1e9320c2ba06d94 这个commit就行

**Comment by Infiheaven** [comment]
非常感谢您的帮助

**Comment by Infiheaven** [comment]
抱歉，为什么revert后变成了这个样子
![image](https://github.com/user-attachments/assets/6bc56709-d9dd-4d8e-9505-4dc02ff1c178)

**Comment by luyanci** [comment]
> 抱歉，为什么revert后变成了这个样子
> ![image](https://github.com/user-attachments/assets/6bc56709-d9dd-4d8e-9505-4dc02ff1c178)
> 

这个我挂个bug吧，出这种问题我是没想到的

**Comment by Infiheaven** [comment]
非常抱歉，请您删除这个Bug标签，因为为了确保可在老设备上使用我使用的是非常古早的几乎JS占60%的版本，刚才在上一个版本的代码中尝试了一下，是没有问题的，所以请您删除这个Bug标签

**Comment by Maizi-G** [comment]
done
